// Generated from specs/public-semantic-source.json; do not edit.
import type { CanonicalReadSnapshot, Digest, HostReadContextData, Identifier, PackageMember, PackageSet, PackageSetHandoff, Selection, UInt, VersionLabel, VersionTuple } from './types.js';
export type PackageSetLocalFailure = "invalid_limits" | "member_limit_exceeded" | "source_bytes_limit_exceeded" | "invalid_member_source" | "invalid_read_request" | "provider_invalid" | "provider_failed" | "provider_observation_invalid" | "cancelled" | "core_unavailable" | "delivery_unconfirmed" | "handoff_invalid";
export type PackageSetLimits = { readonly "maxMembers": 10000; readonly "maxTotalSourceBytes": 104857600; };
export type PackageSetMemberObservationRequest = { readonly "set_id": Identifier; readonly "members": ReadonlyArray<PackageMember>; readonly "selection": Selection; readonly "operation": "isolated_read" | "semantic_merge" | "cross_asset_reference"; readonly "phase": "initial" | "read"; };
export type PackageSetMemberObservationRow = { readonly "member_id": Identifier; readonly "asset_id": Identifier; readonly "asset_version": VersionLabel; readonly "A": Digest; readonly "decision": "allow" | "deny"; readonly "decision_id": Identifier; readonly "host_id": Identifier; readonly "host_epoch": Identifier; readonly "issued_at": UInt; readonly "expires_at": UInt; readonly "current_ms": UInt; };
export type PackageSetMemberObservation = { readonly "decisions": ReadonlyArray<PackageSetMemberObservationRow>; };
export type PackageSetReadObservation = { readonly "context": HostReadContextData; readonly "current_ms": UInt; };
export type PackageSetNodeDescriptor = { readonly "contract": "kdna.package-set-node/0.2.1"; readonly "module_version": "0.2.0"; readonly "core_version": "0.36.0-rc.r2.7"; readonly "read_version": "0.11.0-rc.r2.7"; readonly "limits": PackageSetLimits; readonly "local_failures": ReadonlyArray<PackageSetLocalFailure>; readonly "core_callables": ReadonlyArray<Identifier>; readonly "read_callables": ReadonlyArray<Identifier>; readonly "claims": "claims_not_authenticated"; readonly "definition_digest": Digest; };
export type PackageSetNodeSurface = (PackageSet | PackageSetHandoff | PackageSetMemberObservationRequest | PackageSetMemberObservation | PackageSetReadObservation | PackageSetNodeDescriptor);
export type PackageSetOperation = "isolated_read" | "semantic_merge" | "cross_asset_reference";
export type PackageSetMemberSource = { readonly "member_id": string; readonly "bytes": Uint8Array };
declare const TrustedPackageSetMemberProviderBrand: unique symbol;
export type TrustedPackageSetMemberProvider = { readonly [TrustedPackageSetMemberProviderBrand]: true };
export type PackageSetStructureResult = { readonly "status": "valid"; readonly "value": PackageSet; readonly "proof": "claims_not_authenticated" } | { readonly "status": "rejected"; readonly "diagnostic": "READ_INPUT_INVALID"; readonly "merged_ir": false; readonly "action_authorized": false };
export type PackageSetDecisionAllowed = { readonly "status": "allowed"; readonly "selected_member": string; readonly "merged_ir": false; readonly "action_authorized": false };
export type PackageSetDecisionRejected = { readonly "status": "rejected"; readonly "diagnostic": string; readonly "merged_ir": false; readonly "action_authorized": false };
export type PackageSetDecision = PackageSetDecisionAllowed | PackageSetDecisionRejected;
declare const AdmittedPackageSetBrand: unique symbol;
export type AdmittedPackageSet = { readonly [AdmittedPackageSetBrand]: true };
export type AdmittedPackageSetView = { readonly "set": PackageSet; readonly "tuple": VersionTuple; readonly "operation": PackageSetOperation; readonly "members": ReadonlyArray<{ readonly "member_id": string; readonly "snapshot": CanonicalReadSnapshot }>; readonly "selected_member": { readonly "member_id": string; readonly "snapshot": CanonicalReadSnapshot }; readonly "host_id": string; readonly "host_epoch": string };
export type PackageSetAdmissionResult = { readonly "status": "admitted"; readonly "admission": AdmittedPackageSet; readonly "decision": PackageSetDecisionAllowed; readonly "local_failure": null } | { readonly "status": "rejected"; readonly "admission": null; readonly "decision": PackageSetDecision | null; readonly "local_failure": PackageSetLocalFailure | null };
export type PackageSetRecheckResult = { readonly "status": "allowed"; readonly "decision": PackageSetDecisionAllowed; readonly "local_failure": null } | { readonly "status": "rejected"; readonly "decision": PackageSetDecisionRejected | null; readonly "local_failure": PackageSetLocalFailure | null };
export type PackageSetHandoffResult = { readonly "status": "valid"; readonly "value": PackageSetHandoff; readonly "proof": "claims_not_authenticated" } | { readonly "status": "rejected"; readonly "diagnostic": "handoff_invalid" };
export declare function getPackageSetContract(): PackageSetNodeDescriptor;
export declare function validatePackageSetStructure(input: unknown): PackageSetStructureResult;
export declare function createTrustedPackageSetMemberProvider(config: unknown): TrustedPackageSetMemberProvider;
export declare function admitPackageSetNode(input: unknown, provider: unknown): Promise<PackageSetAdmissionResult>;
export declare function recheckPackageSet(admission: unknown, phase: "read" | "handoff"): PackageSetRecheckResult;
export declare function inspectAdmittedPackageSet(admission: unknown): AdmittedPackageSetView | null;
export declare function verifyPackageSetHandoff(handoff: unknown, admission: unknown, plan: unknown, deliveredRead: unknown): PackageSetHandoffResult;
