'use strict';
const test=require('node:test'),fs=require('node:fs'),fsp=require('node:fs/promises'),os=require('node:os');
const H=require('./protection-test-helpers.js'),{assert,path,crypto,F,req,coreDir,core,read,asset,tuple,policy}=H;
const issuer=req('@aikdna/kdna-core/key-grant-issuer-node');
const parse=require(path.join(coreDir,'src/public-contract/container.js')).parseContainer;
const codec=require(path.join(coreDir,'src/public-contract/protection-envelope-codec.js'));
const digest=b=>'sha256:'+crypto.createHash('sha256').update(b).digest('hex');
async function fixture({catalog=false,badPayload=false,signature=false}={}){
 const a=asset(),root=crypto.randomBytes(32),signer=crypto.generateKeyPairSync('ed25519'),device=crypto.generateKeyPairSync('x25519'),deviceSign=crypto.generateKeyPairSync('ed25519');
 const options={issuer:'issuer:test',signing_key_id:'signer:test',account_id:'account:test',entitlement_id:'entitlement:test',entitlement_profile:'account',device_id:'device:test',device_agreement_public_key:'x25519:'+device.publicKey.export({format:'jwk'}).x,device_signing_public_key:'ed25519:'+deviceSign.publicKey.export({format:'jwk'}).x,grant_id:'grant:explicit',status:'active',status_version:1,issued_at_ms:900,refresh_after_ms:1500,offline_grace_until_ms:1800,expires_at_ms:2000,timeout_ms:60000};
 let bytes;
 if(catalog||badPayload){
  a.manifest.access='licensed';a.manifest.entitlement={profile:'account',offline:true,revocable:true};a.manifest.payload.encrypted=true;a.manifest.encryption={profile:'kdna.envelope.external-grant',profile_version:'0.1.0',encrypted_entries:['payload.kdnab']};
  if(catalog)a.payload.extensions=[{id:'urn:test:unknown',critical:true,definition:'CANARY_UNKNOWN_CONTENT',value:{kind:'text',value:'CANARY_PAYLOAD_PRIVATE'}}];
  if(badPayload)a.payload.asset.asset_version='99.0.0';
  const entries=parse(F.encode(a,req)),plain=Buffer.from(entries['payload.kdnab']),plainDigest=digest(plain),keyRef='key:test',keyId='root:test';
  const aad=Buffer.from(['kdna.envelope.external-grant','0.1.0',a.manifest.asset_uid,a.manifest.asset_id,a.manifest.version,'payload.kdnab',plainDigest,keyRef,keyId,'licensed','account'].join('\n'));
  const cek=Buffer.from(crypto.hkdfSync('sha256',root,crypto.createHash('sha256').update(aad).digest(),Buffer.from('kdna.key-context.asset-content\n'+keyRef),32));
  const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',cek,iv);cipher.setAAD(aad);const encrypted=Buffer.concat([cipher.update(plain),cipher.final()]);
  entries['payload.kdnab']=codec.encodeEnvelope({profile:'kdna.envelope.external-grant',contract_version:'0.1.0',alg:'A256GCM',cek_derivation:'HKDF-SHA256',key_ref:keyRef,issuer_key_id:keyId,entry_path:'payload.kdnab',plaintext_digest:plainDigest,iv:iv.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),ciphertext:encrypted.toString('base64url')});bytes=F.zip(entries);cek.fill(0);
 }else{
  const produced=await core.protectSourceBytes(F.encode(a,req),{kind:'external-grant',asset_uid:a.manifest.asset_uid,entitlement:{profile:'account',offline:true,revocable:true},key_ref:'key:test',issuer_key_id:'root:test',checksums:true,signature:signature?'ed25519':'none'},{issuerRootKey:root,...(signature?{signingSeed:crypto.randomBytes(32)}:{})});assert.equal(produced.status,'produced',JSON.stringify(produced));bytes=produced.bytes;
 }
 const signaturePolicy=signature?{requireSignature:true,expectedPublicKeyHex:JSON.parse(Buffer.from(parse(bytes)['signature.kdsig'])).public_key}:policy;
 const secrets={issuerRootKey:root,issuerSigningPrivateKeyPkcs8:signer.privateKey.export({format:'der',type:'pkcs8'}),signaturePolicy};
 const expected={issuer:options.issuer,signing_key_id:options.signing_key_id,issuer_public_key:'ed25519:'+signer.publicKey.export({format:'jwk'}).x,account_id:options.account_id,entitlement_id:options.entitlement_id,entitlement_profile:'account',device_id:options.device_id,device_agreement_public_key:options.device_agreement_public_key,device_signing_public_key:options.device_signing_public_key};
 const credential=grantBytes=>({kind:'external-grant',grantBytes,deviceAgreementPrivateKeyPkcs8:device.privateKey.export({format:'der',type:'pkcs8'}),mode:'online',expected});
 let revision=0;const provider={kind:'external',clock:()=>1000,capabilities:{offline:true,status_refresh:true,revocation:true},readAdvance:async x=>({scope:x.scope,highest_status_version:x.verified.status_version,status:x.verified.status,last_trusted_time_ms:x.verified.observed_at_ms,revision:++revision}),refresh:async()=>{throw Error('not expected');}};
 return {a,bytes,options,secrets,signer,credential,provider};
}
function noGrant(out,code){assert.equal(out.status,'issuer_failed',JSON.stringify(out));assert.equal(out.code,code);assert.deepEqual(Object.keys(out).sort(),['code','stage','status']);}
test('issuer exports exactly two callables with actual package and fixed limits',()=>{assert.deepEqual(Object.keys(issuer).sort(),['getExternalGrantIssuerContract','issueExternalKeyGrantForAsset']);const d=issuer.getExternalGrantIssuerContract();assert.equal(d.implementation.version,'0.37.0');assert.equal(d.id,'kdna.external-grant-issuer/1');assert.equal(d.limits.max_concurrent,4);});
for(const catalog of [false,true])test('actual final encrypted bytes issue '+(catalog?'unknown critical refuses':'accepted')+' grant at the current R2 boundary',async()=>{
 const f=await fixture({catalog}),out=await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,f.secrets);if(catalog){assert.equal(out.status,'core_rejected',JSON.stringify(out));assert.equal(out.core.reason,'READ_UNSUPPORTED_CRITICAL');assert.equal(out.grantBytes,undefined);assert.ok(!JSON.stringify(out).includes('CANARY_'));return;}assert.equal(out.status,'issued',JSON.stringify(out));assert.equal(out.asset.A,digest(f.bytes));assert.equal(out.grant.digest,digest(out.grantBytes));assert.equal(out.grant.byte_length,out.grantBytes.length);assert.deepEqual(out.admission,{status:catalog?'catalog_only':'accepted',asset_capability:f.a.payload.asset_capability,interpretation:catalog?'blocked':'complete'});assert.ok(!JSON.stringify(out).includes('CANARY_'));
 const admitted=await core.admitProtectedNode(f.bytes,{credential:f.credential(out.grantBytes),signaturePolicy:policy},f.provider);assert.equal(admitted.status,catalog?'catalog_only':'accepted',JSON.stringify(admitted));
 let sink=Buffer.alloc(0);const host=read.createTrustedProtectedHostReadProvider({observe:H.observer(f),async deliver(result,prepared){const commit=await read.commitProtectedTransport(admitted.operation,prepared,{observeScope:H.observer(f),commit:body=>{sink=Buffer.from(JSON.stringify(body));return true;}});assert.equal(commit.status,'committed',JSON.stringify(commit));return true;}});
 const got=await read.readProtectedNode(admitted.operation,F.candidate(tuple,f.a,catalog?'catalog':undefined),H.control(),host);assert.equal(got.status,'read_result',JSON.stringify(got));assert.ok(sink.length>0);assert.equal(got.result.envelope.status,catalog?'catalog_only':'ready');core.disposeProtectionOperation(admitted.operation);
 const evidence=process.env.ARTIFACT_ROOT;if(evidence){fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(path.join(evidence,catalog?'catalog.kdna':'accepted.kdna'),f.bytes);fs.writeFileSync(path.join(evidence,catalog?'catalog-sink.json':'accepted-sink.json'),sink);fs.writeFileSync(path.join(evidence,catalog?'catalog-observation.json':'accepted-observation.json'),JSON.stringify({...out,grantBytes:undefined},null,2));}
});
test('issuer cryptographic and integrity failures cannot issue or downgrade to catalog',async()=>{
 const f=await fixture({signature:true});noGrant(await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,{...f.secrets,issuerRootKey:crypto.randomBytes(32)}),'ISSUER_ASSET_AUTHENTICATION_FAILED');noGrant(await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,{...f.secrets,signaturePolicy:{requireSignature:true,expectedPublicKeyHex:'00'.repeat(32)}}),'ISSUER_ASSET_AUTHENTICATION_FAILED');
 const plain=await fixture({catalog:true});for(const field of ['tag','issuer_key_id','key_ref','plaintext_digest']){const entries=parse(plain.bytes),envelope=codec.decodeEnvelope(entries['payload.kdnab']);envelope[field]=field==='tag'?Buffer.alloc(16).toString('base64url'):field==='plaintext_digest'?'sha256:'+'0'.repeat(64):'wrong';entries['payload.kdnab']=codec.encodeEnvelope(envelope);noGrant(await issuer.issueExternalKeyGrantForAsset(F.zip(entries),plain.options,plain.secrets),'ISSUER_ASSET_AUTHENTICATION_FAILED');}
 for(const wire of [Buffer.from('{}'),Buffer.from([0xbf,0xff])]){const entries=parse(plain.bytes);entries['payload.kdnab']=wire;noGrant(await issuer.issueExternalKeyGrantForAsset(F.zip(entries),plain.options,plain.secrets),'ISSUER_ASSET_AUTHENTICATION_FAILED');}
 const bad=await fixture({badPayload:true}),result=await issuer.issueExternalKeyGrantForAsset(bad.bytes,bad.options,bad.secrets);assert.deepEqual(result,{status:'core_rejected',stage:'asset',core:{status:'rejected',reason:'READ_CORE_INVALID'}});
});
test('plain and password profiles are not arbitrary grant inputs',async()=>{const f=await fixture(),plain=F.encode(f.a,req);noGrant(await issuer.issueExternalKeyGrantForAsset(plain,f.options,f.secrets),'ISSUER_ASSET_PROFILE_UNSUPPORTED');const pw=await core.protectSourceBytes(plain,{kind:'password',asset_uid:f.a.manifest.asset_uid,entitlement:{profile:'password'},slots:[{slot:'s',kdf_profile:'scrypt-sha256'}],checksums:false,signature:'none'},{passwords:[{slot:'s',password:Buffer.from('synthetic')}]});noGrant(await issuer.issueExternalKeyGrantForAsset(pw.bytes,f.options,f.secrets),'ISSUER_ASSET_PROFILE_UNSUPPORTED');});
test('closed capture rejects getters proxies symbols shared bytes and caller authority carriers',async()=>{const f=await fixture();let calls=0;const getter={...f.options};Object.defineProperty(getter,'issuer',{get(){calls++;return 'issuer:test';},enumerable:true});for(const options of [getter,new Proxy(f.options,{get(){calls++;throw Error();}}),{...f.options,[Symbol('x')]:1},...['A','CEK','manifest','envelope','verified'].map(k=>({...f.options,[k]:true}))])noGrant(await issuer.issueExternalKeyGrantForAsset(f.bytes,options,f.secrets),'ISSUER_INPUT_INVALID');noGrant(await issuer.issueExternalKeyGrantForAsset(new Uint8Array(new SharedArrayBuffer(10)),f.options,f.secrets),'ISSUER_INPUT_INVALID');assert.equal(calls,0);});
test('six closed families preserve options key and malformed core rejection',async()=>{const f=await fixture();for(const delta of [{status_version:0},{refresh_after_ms:899},{timeout_ms:0},{device_agreement_public_key:'x25519:'+'A'.repeat(42)+'B'}])noGrant(await issuer.issueExternalKeyGrantForAsset(f.bytes,{...f.options,...delta},f.secrets),'ISSUER_GRANT_OPTIONS_INVALID');for(const delta of [{issuerRootKey:Buffer.alloc(31)},{issuerSigningPrivateKeyPkcs8:Buffer.alloc(32)},{issuerSigningPrivateKeyPkcs8:Buffer.concat([f.secrets.issuerSigningPrivateKeyPkcs8,Buffer.from([0])])}])noGrant(await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,{...f.secrets,...delta}),'ISSUER_KEY_INVALID');assert.equal((await issuer.issueExternalKeyGrantForAsset(Buffer.from('badzip'),f.options,f.secrets)).status,'core_rejected');});
test('signed states are explicit and inactive grant cannot gain device admission',async()=>{const f=await fixture();for(const status of ['active','revoked','expired']){const out=await issuer.issueExternalKeyGrantForAsset(f.bytes,{...f.options,status},f.secrets);assert.equal(out.status,'issued');const grant=JSON.parse(Buffer.from(out.grantBytes));assert.equal(grant.status,status);assert.equal(grant.grant_id,'grant:explicit');assert.equal(Date.parse(grant.issued_at),900);const admitted=await core.admitProtectedNode(f.bytes,{credential:f.credential(out.grantBytes),signaturePolicy:policy},f.provider);assert.equal(admitted.status,status==='active'?'accepted':'protection_failed');}});
test('same E repack binds new captured A and old grant fails',async()=>{const f=await fixture(),old=await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,f.secrets),repacked=F.zip(parse(f.bytes),{deflate:true}),next=await issuer.issueExternalKeyGrantForAsset(repacked,f.options,f.secrets);assert.equal(next.status,'issued');assert.equal(next.asset.E,old.asset.E);assert.notEqual(next.asset.A,old.asset.A);assert.equal((await core.admitProtectedNode(repacked,{credential:f.credential(old.grantBytes),signaturePolicy:policy},f.provider)).diagnostic.code,'PROTECTION_GRANT_BINDING_MISMATCH');});
test('capture uses original mutable arguments and actual bounded file bytes',async()=>{const f=await fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'issuer-')),file=path.join(dir,'asset.kdna');fs.writeFileSync(file,f.bytes);const options={...f.options},secrets={...f.secrets,issuerRootKey:Buffer.from(f.secrets.issuerRootKey),issuerSigningPrivateKeyPkcs8:Buffer.from(f.secrets.issuerSigningPrivateKeyPkcs8)},pending=issuer.issueExternalKeyGrantForAsset(file,options,secrets);options.account_id='wrong';secrets.issuerRootKey.fill(0);secrets.issuerSigningPrivateKeyPkcs8.fill(0);const out=await pending;assert.equal(out.status,'issued',JSON.stringify(out));assert.equal(JSON.parse(Buffer.from(out.grantBytes)).account_id,'account:test');assert.equal(out.asset.A,digest(fs.readFileSync(file)));fs.rmSync(dir,{recursive:true});});
async function ownedDeadlineEvidence(phases){
 const f=await fixture(),entry=req.resolve('@aikdna/kdna-core/key-grant-issuer-node');
 const input={bytes:Buffer.from(f.bytes).toString('base64'),options:f.options,secrets:{...f.secrets,issuerRootKey:f.secrets.issuerRootKey.toString('base64'),issuerSigningPrivateKeyPkcs8:f.secrets.issuerSigningPrivateKeyPkcs8.toString('base64')}};
 const child=require('node:child_process').spawnSync(process.execPath,[path.join(__dirname,'issuer-owned-io-worker.cjs'),entry,...phases],{input:JSON.stringify(input),encoding:'utf8',timeout:30000,env:{...process.env,NODE_PATH:''}});
 assert.equal(child.status,0,child.stdout+child.stderr+String(child.error??''));assert.equal(child.signal,null);
 const evidence=JSON.parse(child.stdout);assert.equal(evidence.entry,entry);assert.deepEqual(evidence.rows.map(x=>x.phase),phases);
 for(const row of evidence.rows){
  assert.equal(row.control.output.status,'issued');assert.equal(row.control.signed,1);assert.equal(row.control.verified,1);assert.equal(row.control.closed,1);assert.equal(row.control.reached,1);
  assert.equal(row.timed_out.reached,4);assert.equal(row.timed_out.opened,4);assert.equal(row.timed_out.timers_fired,4);
  for(const out of row.timed_out.outputs){noGrant(out,'ISSUER_OUTPUT_INVALID');assert.equal(out.stage,'input');}
  noGrant(row.timed_out.busy,'ISSUER_INPUT_INVALID');assert.equal(row.timed_out.busy.stage,'input');
  assert.equal(row.timed_out.closed_before_release,0);assert.equal(row.timed_out.closed,4);assert.equal(row.timed_out.signed_before_recovery,0);
  assert.equal(row.timed_out.recovery.status,'issued');assert.equal(row.timed_out.recovery.signed,1);assert.equal(row.timed_out.recovery.verified,1);
 }
 if(process.env.ARTIFACT_ROOT){fs.mkdirSync(process.env.ARTIFACT_ROOT,{recursive:true});fs.writeFileSync(path.join(process.env.ARTIFACT_ROOT,'issuer-owned-'+phases.join('-')+'.json'),JSON.stringify(evidence,null,2)+'\n');}
}
test('four timed out owned opens retain slots until late handles close and never sign',async()=>{await ownedDeadlineEvidence(['open']);});
test('unchanged synchronous helper may cross deadline but cannot publish grant',async()=>{
 const f=await fixture(),entry=req.resolve('@aikdna/kdna-core/key-grant-issuer-node');
 const input={bytes:Buffer.from(f.bytes).toString('base64'),options:f.options,secrets:{...f.secrets,issuerRootKey:f.secrets.issuerRootKey.toString('base64'),issuerSigningPrivateKeyPkcs8:f.secrets.issuerSigningPrivateKeyPkcs8.toString('base64')}};
 const child=require('node:child_process').spawnSync(process.execPath,[path.join(__dirname,'issuer-deadline-worker.cjs'),entry],{input:JSON.stringify(input),encoding:'utf8',env:{...process.env,NODE_PATH:''}});
 assert.equal(child.status,0,child.stdout+child.stderr);assert.equal(child.signal,null);
 const evidence=JSON.parse(child.stdout);assert.equal(evidence.entry,entry);
 assert.equal(evidence.control.invoked,1);assert.equal(evidence.control.signature_verified,true);assert.equal(evidence.control.output.status,'issued');
 assert.equal(evidence.crossed.invoked,1);assert.equal(evidence.crossed.signature_verified,true);assert.ok(evidence.crossed.after_sign_expired_samples>0);
 noGrant(evidence.crossed.output,'ISSUER_OUTPUT_INVALID');assert.equal(evidence.crossed.output.stage,'grant');
 if(process.env.ARTIFACT_ROOT){fs.mkdirSync(process.env.ARTIFACT_ROOT,{recursive:true});fs.writeFileSync(path.join(process.env.ARTIFACT_ROOT,'issuer-deadline.json'),JSON.stringify(evidence,null,2)+'\n');}
});
test('owned late stat read and close never release a slot before actual settle',async()=>{await ownedDeadlineEvidence(['stat','read','close']);});
test('closed output and caller buffer mutation do not create a reusable authority',async()=>{
 const f=await fixture(),out=await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,f.secrets);assert.deepEqual(Object.keys(out).sort(),['admission','asset','grant','grantBytes','issuer','proof','status']);assert.equal(core.bindProtectionOperation(out).status,'protection_failed');assert.equal(H.boundary.inspectSnapshot(out),null);const before=digest(f.bytes);out.grantBytes.fill(0);assert.equal(digest(f.bytes),before);assert.equal((await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,f.secrets)).status,'issued');
 const nested={...f.secrets,signaturePolicy:{requireSignature:false,get expectedPublicKeyHex(){throw Error('getter must not execute');}}};noGrant(await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,nested),'ISSUER_INPUT_INVALID');
 for(const input of ['relative.kdna','/missing/synthetic/issuer.kdna',new Uint8Array(26214401)])noGrant(await issuer.issueExternalKeyGrantForAsset(input,f.options,f.secrets),'ISSUER_INPUT_INVALID');
});

test('all source shape capture precedes real forwarded key crypto, including malformed DER combination',async()=>{
 const f=await fixture(),rows=[];let trace=[],traps=0;
 const old={createPrivateKey:crypto.createPrivateKey,createPublicKey:crypto.createPublicKey,createDecipheriv:crypto.createDecipheriv,sign:crypto.sign,open:fsp.open};
 crypto.createPrivateKey=function(...args){trace.push('createPrivateKey');const key=old.createPrivateKey.apply(this,args),exportKey=key.export;key.export=function(...parts){trace.push('privateKey.export');return exportKey.apply(this,parts);};return key;};
 crypto.createPublicKey=function(...args){trace.push('createPublicKey');const key=old.createPublicKey.apply(this,args),exportKey=key.export;key.export=function(...parts){trace.push('publicKey.export');return exportKey.apply(this,parts);};return key;};
 crypto.createDecipheriv=function(...args){trace.push('createDecipheriv');return old.createDecipheriv.apply(this,args);};
 crypto.sign=function(...args){trace.push('sign');return old.sign.apply(this,args);};
 fsp.open=async function(...args){trace.push('file.open');const handle=await old.open.apply(this,args);for(const name of ['stat','read','close']){const actual=handle[name];handle[name]=function(...parts){trace.push('file.'+name);return actual.apply(this,parts);};}return handle;};
 const cases=[['relative-path',()=> 'relative.kdna'],['NUL-absolute-path',()=>path.join(os.tmpdir(),'nul\0asset')],['plain-record',()=>({bytes:new Uint8Array([1])})],['proxy',()=>new Proxy({},{get(){traps++;throw Error();},getPrototypeOf(){traps++;throw Error();},ownKeys(){traps++;throw Error();}})],['proxy-Uint8Array',()=>new Proxy(new Uint8Array([1]),{})],['shared-bytes',()=>new Uint8Array(new SharedArrayBuffer(3))],['empty-bytes',()=>new Uint8Array()],['oversize-bytes',()=>new Uint8Array(26214401)]];
 const record=(name,out)=>rows.push({name,output:out,trace:[...trace],getter_or_trap:traps,file_calls:trace.filter(x=>x.startsWith('file.')).length,key_crypto_calls:trace.filter(x=>['createPrivateKey','privateKey.export','createPublicKey','publicKey.export'].includes(x)).length,sign_calls:trace.filter(x=>x==='sign').length,decrypt_calls:trace.filter(x=>x==='createDecipheriv').length,grant_outputs:out.status==='issued'?1:0});
 try{
  for(const [name,make]of cases)for(const badDer of [false,true]){trace=[];traps=0;const out=await issuer.issueExternalKeyGrantForAsset(make(),f.options,badDer?{...f.secrets,issuerSigningPrivateKeyPkcs8:Buffer.from([1])}:f.secrets);assert.deepEqual(out,{status:'issuer_failed',code:'ISSUER_INPUT_INVALID',stage:'input'});assert.deepEqual(trace,[],name);assert.equal(traps,0,name);record(name+(badDer?'-plus-badDER':''),out);}
  for(const field of ['options','secrets']){trace=[];traps=0;const value={...(field==='options'?f.options:f.secrets)},name=field==='options'?'issuer':'issuerRootKey';Object.defineProperty(value,name,{enumerable:true,get(){traps++;throw Error();}});const out=await issuer.issueExternalKeyGrantForAsset(f.bytes,field==='options'?value:f.options,field==='secrets'?value:f.secrets);assert.equal(out.code,'ISSUER_INPUT_INVALID');assert.deepEqual(trace,[]);assert.equal(traps,0);record(field+'-getter-control',out);}
  trace=[];const bad=await issuer.issueExternalKeyGrantForAsset(Buffer.from([1,2,3]),f.options,f.secrets);assert.equal(bad.status,'core_rejected');assert.deepEqual(trace,['createPrivateKey','privateKey.export','createPublicKey','publicKey.export']);record('shape-valid-bad-container-forwarding-control',bad);
  trace=[];const valid=await issuer.issueExternalKeyGrantForAsset(f.bytes,f.options,f.secrets);assert.equal(valid.status,'issued');assert.ok(trace.includes('createPrivateKey'));assert.ok(trace.includes('createPublicKey'));assert.ok(trace.includes('createDecipheriv'));assert.equal(trace.filter(x=>x==='sign').length,1);record('valid-asset-forwarding-control',{...valid,grantBytes:undefined});
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'issuer-shape-'));
  try{
   trace=[];const missing=await issuer.issueExternalKeyGrantForAsset(path.join(directory,'missing.kdna'),f.options,f.secrets);assert.equal(missing.code,'ISSUER_INPUT_INVALID');assert.ok(trace.includes('createPrivateKey'));assert.equal(trace.filter(x=>x==='file.open').length,1);assert.ok(!trace.includes('sign')&&!trace.includes('createDecipheriv'));record('actual-missing-file-known-only-after-io',missing);
   const large=path.join(directory,'oversize.kdna'),fd=fs.openSync(large,'wx',0o600);try{fs.ftruncateSync(fd,26214401);}finally{fs.closeSync(fd);}
   trace=[];const oversized=await issuer.issueExternalKeyGrantForAsset(large,f.options,f.secrets);assert.equal(oversized.code,'ISSUER_INPUT_INVALID');assert.deepEqual(trace.filter(x=>x.startsWith('file.')),['file.open','file.stat','file.close']);assert.ok(!trace.includes('sign')&&!trace.includes('createDecipheriv'));record('actual-oversized-file-closes-owner',oversized);
  }finally{fs.rmSync(directory,{recursive:true});}
 }finally{Object.assign(crypto,{createPrivateKey:old.createPrivateKey,createPublicKey:old.createPublicKey,createDecipheriv:old.createDecipheriv,sign:old.sign});fsp.open=old.open;}
 const evidence=process.env.ARTIFACT_ROOT;if(evidence){fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(path.join(evidence,'issuer-input-order.json'),JSON.stringify({node:process.version,execPath:process.execPath,TMPDIR:process.env.TMPDIR,KDNA_PUBLIC_RUNTIME:process.env.KDNA_PUBLIC_RUNTIME??null,resolved_entry:req.resolve('@aikdna/kdna-core/key-grant-issuer-node'),instrumentation:'Every crypto/file wrapper forwards to the original Node function; issued control has actual decrypt/sign and output. grant_outputs counts actual issued results, not a private helper hook.',rows},null,2)+'\n');}
});
