import type { PackageSet } from './types.js';
import type { Identifier, Selection, CandidateVersionTuple06, WholeSectionSnapshot06, AdmittedSectionReadRequest06 } from './sections/types.js';
import type { NativeSectionByteReadAuthority06 } from './sectionbytes/types.js';
import type { AdmittedNativeConsumptionPlan06 } from './execution06/types.js';
import type { NativePackageSetDescriptor06, NativePackageSetLimits06, NativePackageSetOperation06, NativePackageSetMemberObservationRequest06, NativePackageSetMemberObservation06, NativePackageSetStructureResult06, TrustedNativePackageSetMemberProvider06, AdmittedNativePackageSet06, NativePackageSetAdmissionResult06, NativePackageSetRecheckResult06, NativePackageSetView06, DeliveredNativePackageRead06, NativePackageSetHandoffResult06 } from './packageset06/types.js';
export type * from './packageset06/types.js';
export type { PackageSet } from './types.js';
export type { Identifier, Selection, CandidateVersionTuple06, WholeSectionSnapshot06, AdmittedSectionReadRequest06 } from './sections/types.js';
export type { NativeSectionByteReadAuthority06 } from './sectionbytes/types.js';
export type { AdmittedNativeConsumptionPlan06 } from './execution06/types.js';
export type NativePackageSetMemberSource06 = Readonly<{ member_id: Identifier; bytes: Uint8Array; request: AdmittedSectionReadRequest06; authority: NativeSectionByteReadAuthority06 }>;
export type NativePackageSetInput06 = Readonly<{ set: PackageSet; tuple: CandidateVersionTuple06; operation: NativePackageSetOperation06; limits: NativePackageSetLimits06; members: ReadonlyArray<NativePackageSetMemberSource06> }>;
export type NativePackageSetMemberProviderConfig06 = Readonly<{ host_id: Identifier; host_epoch: Identifier; observe: (request: Readonly<NativePackageSetMemberObservationRequest06>) => NativePackageSetMemberObservation06 }>;
export declare function getNativePackageSetContract(): NativePackageSetDescriptor06;
export declare function validateNativePackageSetStructure(input: unknown): NativePackageSetStructureResult06;
export declare function createTrustedNativePackageSetMemberProvider(config: NativePackageSetMemberProviderConfig06): TrustedNativePackageSetMemberProvider06;
export declare function admitNativePackageSetNode(input: NativePackageSetInput06, provider: TrustedNativePackageSetMemberProvider06): Promise<NativePackageSetAdmissionResult06>;
export declare function recheckNativePackageSet(admission: AdmittedNativePackageSet06, phase: 'read'|'handoff'): NativePackageSetRecheckResult06;
export declare function inspectAdmittedNativePackageSet(admission: AdmittedNativePackageSet06): Readonly<NativePackageSetView06>|null;
export declare function verifyNativePackageSetHandoff(wire: unknown, admission: AdmittedNativePackageSet06, plan: AdmittedNativeConsumptionPlan06, delivered: DeliveredNativePackageRead06): NativePackageSetHandoffResult06;
