// Source-bound owned-byte admission structural types; opaque byte-read authorities require native construction.
export type AssetIdentity = { readonly "asset_id": Identifier; readonly "asset_version": VersionLabel; readonly "judgment_version": VersionLabel; };
export type CandidateVersionTuple06 = { readonly "container": "0.6.0"; readonly "payload_profile": "kdna.payload.judgment"; readonly "payload_version": "0.5.1"; readonly "core": "kdna.core/0.8.2"; readonly "ir": "kdna.canonical-ir/0.6.1"; readonly "runtime": "kdna.runtime-capsule/0.3.1"; readonly "plan": "kdna.consumption-plan/0.3.1"; readonly "host": "kdna.agent-host/0.3.1"; readonly "trace": "kdna.judgment-trace/0.3.1"; readonly "read": "kdna.read/0.7.0-candidate"; };
export type CapturedInput06 = { readonly "capture_id": Identifier; readonly "input_byte_length": UInt; readonly "manifest_bytes_digest": Digest; readonly "zip_directory_bytes_digest": Digest; readonly "table_frames": ReadonlyArray<CheckedSection06>; readonly "identity_scope": "observed_metadata_and_loaded_sections_only"; };
export type CheckedSection06 = { readonly "section_id": Identifier; readonly "member": EntryName; readonly "offset_bytes": UInt; readonly "length_bytes": number; readonly "digest": Digest; };
export type Digest = string;
export type EntryName = string;
export type Identifier = string;
export type NativeSectionByteAccepted06 = { readonly "status": "accepted"; readonly "snapshot": WholeSectionSnapshot06; readonly "input_observation": NativeSectionByteObservation06; };
export type NativeSectionByteAdmissionResult06 = (NativeSectionByteAccepted06 | NativeSectionByteRejected06);
export type NativeSectionByteAuthorityContext06 = { readonly "contract": NativeSectionByteContract06; readonly "operation": "admit_owned_whole"; readonly "request": Request06_whole_asset; readonly "request_digest": Digest; readonly "input_observation": NativeSectionByteObservation06; readonly "manifest_identity": AssetIdentity; readonly "signature_policy": SectionSignaturePolicy06; readonly "signature_policy_digest": Digest; readonly "signature_read_intent": SectionSignatureReadIntent06; readonly "signature_read_intent_digest": Digest; };
export type NativeSectionByteContract06 = { readonly "id": "kdna.section-bytes-node"; readonly "version": "0.1.1-candidate"; readonly "definition_digest": Digest; };
export type NativeSectionByteObservation06 = { readonly "contract": NativeSectionByteContract06; readonly "input_kind": "owned_uint8array"; readonly "input_byte_length": UInt; readonly "ownership_copy": { readonly "offset_bytes": 0; readonly "length_bytes": UInt; }; readonly "capture": (CapturedInput06 | null); readonly "access_ranges": ReadonlyArray<SectionIORange06>; readonly "filesystem_reads": 0; };
declare const NativeSectionByteReadAuthority06Brand: unique symbol;
export type NativeSectionByteReadAuthority06 = { readonly [NativeSectionByteReadAuthority06Brand]: true };
export type NativeSectionByteRejected06 = { readonly "contract": NativeSectionByteContract06; readonly "status": "rejected" | "unsupported"; readonly "request_id": (Identifier | null); readonly "stage": "input" | "metadata" | "authorization" | "content" | "semantic" | "integrity"; readonly "reason": NonEmptyText; readonly "diagnostic": (SectionFailureDiagnostic06 | null); readonly "input_observation": (NativeSectionByteObservation06 | null); readonly "snapshot": null; };
export type NonEmptyText = string;
export type Request06_whole_asset = { readonly "request_id": Identifier; readonly "tuple": CandidateVersionTuple06; readonly "budget_bytes": UInt; readonly "mode": "whole_asset"; readonly "selection": null; readonly "handle": null; };
export type SectionFailureDiagnostic06 = { readonly "field": (Text | null); readonly "subject": (Identifier | null); };
export type SectionIORange06 = (SectionIOSingleRange06 | SectionIOStructureBatch06);
export type SectionIOSingleRange06 = { readonly "offset_bytes": UInt; readonly "length_bytes": UInt; readonly "purpose": "zip_end" | "zip_directory" | "zip_local_header" | "zip_local_name" | "mimetype" | "manifest" | "whole_after_authorization" | "zip_directory_header" | "zip_directory_name" | "section_table_after_authorization" | "section_content_after_authorization" | "resource_after_authorization" | "section_structure_after_authorization" | "zip_locator_local_signature" | "zip_locator_local_header" | "zip_locator_directory_signature" | "zip_locator_directory_header" | "zip_locator_directory_name" | "zip_locator_local_name" | "zip_locator_eocd" | "zip_comment" | "checksum_document_after_authorization" | "checksum_member_after_authorization" | "signature_document_after_authorization" | "signature_member_after_authorization"; };
export type SectionIOStructureBatch06 = { readonly "purpose": "section_structure_after_authorization" | "section_interpretation_after_authorization"; readonly "ranges": ReadonlyArray<{ readonly "offset_bytes": UInt; readonly "length_bytes": UInt; }>; };
export type SectionSignaturePolicy06 = { readonly "requireSignature": boolean; readonly "expectedPublicKeyHex": (string | null); };
export type SectionSignatureReadIntent06 = ({ readonly "operation": "none"; } | { readonly "operation": "verify_complete_original_kdsig_domain"; readonly "signature_member": SectionSignatureReadMember06; readonly "covered_members": ReadonlyArray<SectionSignatureReadMember06>; readonly "excluded_members": ReadonlyArray<EntryName>; readonly "profile": "kdsig.ed25519"; readonly "profile_version": "0.1.0"; });
export type SectionSignatureReadMember06 = { readonly "name": EntryName; readonly "bytes": number; };
export type Text = string;
export type UInt = number;
export type VersionLabel = Identifier;
import type { WholeSectionSnapshot06 } from '../sections/types.js';
export type { WholeSectionSnapshot06 } from '../sections/types.js';
