import type { NativePackageSetDescriptor06, AdmittedNativePackageSet06, DeliveredNativePackageRead06, TrustedNativePackageReadProvider06, NativePackageSetReadResult06, NativePackageSetHandoffResult06, AdmittedNativeConsumptionPlan06 } from '@aikdna/kdna-core/package-set-sections-node';
import type { Identifier, AdmittedRetainedSectionRequest06, RetainedSectionReadAuthority06, RetainedSectionRequest06, WholeSectionSnapshot06, RetainedSectionPreparationData06, RetainedSectionHostObservation06, RetainedSectionReadCallResult06 } from '@aikdna/kdna-core/retained-sections-node';
export type { NativePackageSetReadResult06, NativePackageSetHandoffResult06, DeliveredNativePackageRead06, TrustedNativePackageReadProvider06 } from '@aikdna/kdna-core/package-set-sections-node';
export type NativePackageReadProviderConfig06 = Readonly<{ host_id: Identifier; host_epoch: Identifier; observeRead: (context: Readonly<{ request: RetainedSectionRequest06; snapshot: WholeSectionSnapshot06; preparation: RetainedSectionPreparationData06 }>) => RetainedSectionHostObservation06|Promise<RetainedSectionHostObservation06>; sink?: (result: RetainedSectionReadCallResult06) => boolean }>;
export declare function getNativePackageReadContract(): NativePackageSetDescriptor06;
export declare function createTrustedNativePackageReadProvider(config: NativePackageReadProviderConfig06): TrustedNativePackageReadProvider06;
export declare function readNativePackageSet(admission: AdmittedNativePackageSet06, request: AdmittedRetainedSectionRequest06, authority: RetainedSectionReadAuthority06, provider: TrustedNativePackageReadProvider06, signal?: AbortSignal): Promise<NativePackageSetReadResult06>;
export declare function sealNativePackageSetHandoff(delivered: DeliveredNativePackageRead06, plan: AdmittedNativeConsumptionPlan06): NativePackageSetHandoffResult06;
export declare function admitNativePackageSetHandoff(wire: unknown, delivered: DeliveredNativePackageRead06, plan: AdmittedNativeConsumptionPlan06): NativePackageSetHandoffResult06;
