'use strict';
const {hosts}=require('./brands.js'),{clone,freeze,jcs}=require('./util.js'),{canonicalDigest}=require('./section-host-gate.js');
const lineage=new WeakMap();let sequence=0;
function originValue(view){const c=view.verification.capture;return {snapshot_id:view.snapshot_id,request_digest:view.request_digest??view.verification.request_digest,capture_id:c.capture_id,input_byte_length:c.input_byte_length,manifest_bytes_digest:c.manifest_bytes_digest,zip_directory_bytes_digest:c.zip_directory_bytes_digest,checked_sections_digest:canonicalDigest(view.verification.checked_sections)};}
function lookup(provider,handle){const state=hosts.get(provider);if(!state||!state.handles.has(handle.handle_id)||jcs(state.handles.get(handle.handle_id))!==jcs(handle))return {error:'READ_HANDLE_UNTRUSTED'};const origin=lineage.get(state)?.get(handle.handle_id);return origin?{snapshot:origin}:{error:'READ_HANDLE_UNTRUSTED'};}
function scopeTargets(body,view,context){const allowed=new Set(context.scope),targets=new Map(view.expansion_targets.map(x=>[jcs(x.target),x]));return body.content.asset_index.every(row=>row.body_delivery==='inline'||(targets.has(jcs(row.target))&&targets.get(jcs(row.target)).scope.every(id=>allowed.has(id))));}
function mint(body,view,context){const targets=new Map(view.expansion_targets.map(x=>[jcs(x.target),x])),handles=[],origin=originValue(view);for(const row of body.content.asset_index){if(row.body_delivery==='inline')continue;const proof=targets.get(jcs(row.target));if(!proof)throw Error('READ_PROJECTION_INVALID');const handle={binding_kind:'section_capture',handle_id:'section-handle:'+view.snapshot_id+':'+(++sequence),asset:clone(view.asset),tuple:clone(view.tuple),origin:clone(origin),anchor:clone(proof.anchor),target:clone(proof.target),scope:clone(proof.scope),issued_at:context.current_ms,expires_at:Math.min(context.expires_at,context.current_ms+3600000),host_id:context.host_id,host_epoch:context.host_epoch};handles.push(handle);row.body_delivery='deferred';row.handle_id=handle.handle_id;for(const omission of body.omissions)if(omission.target===row.node_ref){omission.expandable=true;omission.handle_id=handle.handle_id;omission.reason='not_requested';}}body.content.expansion_handles=handles;return handles;}
function commit(state,handles,current,snapshot){let origins=lineage.get(state);if(!origins){origins=new Map();lineage.set(state,origins);}for(const [id,h]of state.handles)if(current>=h.expires_at){state.handles.delete(id);origins.delete(id);}for(const h of handles){state.handles.set(h.handle_id,freeze(clone(h)));origins.set(h.handle_id,snapshot);}}
module.exports={lookup,scopeTargets,mint,commit};
