// Generated from specs/public-semantic-source.json; do not edit.
import type { AssetIdentity, Digest, Identifier, ReadAdmissionRejection, ReadCorrelation, ReadDiagnosticCode, ReadEnvelope, UInt, VersionTuple } from '@aikdna/kdna-core';
export type ReadTransportContext = { readonly "association_id": Identifier; readonly "endpoint_id": Identifier; readonly "session_id": Identifier; readonly "endpoint_url": string; readonly "issued_at_ms": UInt; readonly "expires_at_ms": UInt; readonly "outbound_request_json": string; readonly "correlation": ReadCorrelation; readonly "expected_tuple": VersionTuple; readonly "expected_asset": AssetIdentity; readonly "expected_digests": { readonly "A": Digest; readonly "C": Digest; readonly "E": Digest; }; readonly "expected_snapshot_id": (Identifier | null); readonly "max_response_bytes": number; readonly "max_read_ms": number; readonly "admission_response_limit_bytes": number; };
export type ReadTransportAssociation = { readonly "association_id": Identifier; readonly "endpoint_id": Identifier; readonly "session_id": Identifier; readonly "correlation": ReadCorrelation; };
export type ReadTransportProofScope = { readonly "response_url_matched": boolean; readonly "bounded_bytes": boolean; readonly "strict_json": boolean; readonly "schema": boolean; readonly "observable_bindings": boolean; readonly "process_association_once": boolean; readonly "fetch_visible_http": boolean; };
export type ReadTransportProofLimits = { readonly "remote_identity": "NOT_PROVEN"; readonly "remote_authorization": "NOT_PROVEN"; readonly "current_remote_revocation": "NOT_PROVEN"; readonly "core_semantics": "NOT_REVALIDATED"; readonly "receipt_delivery": "REMOTE_CLAIM_ONLY"; readonly "network_replay": "NOT_PROVEN"; readonly "local_capabilities": "NONE"; readonly "raw_http_framing": "NOT_OBSERVABLE_THROUGH_FETCH"; };
export type ReadTransportCapabilities = { readonly "core_snapshot": false; readonly "admitted_request": false; readonly "host_witness": false; readonly "authorization": false; readonly "action": false; };
export type ReadTransportControlHeaders = { readonly "code": "READ_ADMISSION_RESPONSE_TOO_SMALL" | "READ_RESPONSE_BUDGET_TOO_SMALL"; readonly "semantic_cause": (ReadDiagnosticCode | null); };
export type ReadTransportFailureHeaders = { readonly "code": "READ_TRANSPORT_FAILURE"; readonly "semantic_cause": (ReadDiagnosticCode | null); };
export type RemoteReadEnvelope = { readonly "channel": "read_envelope"; readonly "http_status": 200 | 422; readonly "byte_length": UInt; readonly "body": ReadEnvelope; readonly "headers": null; };
export type RemoteReadAdmissionRejection = { readonly "channel": "admission_rejection"; readonly "http_status": 422; readonly "byte_length": UInt; readonly "body": ReadAdmissionRejection; readonly "headers": null; };
export type RemoteReadNoBodyControl = { readonly "channel": "no_body_control"; readonly "http_status": 413; readonly "byte_length": UInt; readonly "body": null; readonly "headers": ReadTransportControlHeaders; };
export type RemoteReadTransportFailure = { readonly "channel": "transport_failure"; readonly "http_status": 502; readonly "byte_length": UInt; readonly "body": null; readonly "headers": ReadTransportFailureHeaders; };
export type ReadTransportRemoteResponse = (RemoteReadEnvelope | RemoteReadAdmissionRejection | RemoteReadNoBodyControl | RemoteReadTransportFailure);
export type ReadTransportRejection = { readonly "code": "READ_TRANSPORT_RESPONSE_INVALID" | "READ_TRANSPORT_CONTEXT_INVALID" | "READ_TRANSPORT_ASSOCIATION_STALE" | "READ_TRANSPORT_ASSOCIATION_REPLAYED" | "READ_TRANSPORT_ASSOCIATION_CAPACITY" | "READ_TRANSPORT_LIMIT_EXCEEDED" | "READ_TRANSPORT_TIMEOUT" | "READ_TRANSPORT_HTTP_MISMATCH" | "READ_TRANSPORT_JSON_INVALID" | "READ_TRANSPORT_SCHEMA_INVALID" | "READ_TRANSPORT_BINDING_MISMATCH"; };
export type ReadTransportAccepted = { readonly "contract": "kdna.read-transport-admission/0.1.0"; readonly "origin": "remote"; readonly "proof_scope": ReadTransportProofScope; readonly "proof_limits": ReadTransportProofLimits; readonly "capabilities": ReadTransportCapabilities; readonly "status": "accepted"; readonly "association": ReadTransportAssociation; readonly "response": ReadTransportRemoteResponse; readonly "rejection": null; };
export type ReadTransportRejected = { readonly "contract": "kdna.read-transport-admission/0.1.0"; readonly "origin": "remote"; readonly "proof_scope": ReadTransportProofScope; readonly "proof_limits": ReadTransportProofLimits; readonly "capabilities": ReadTransportCapabilities; readonly "status": "rejected"; readonly "association": (ReadTransportAssociation | null); readonly "response": null; readonly "rejection": ReadTransportRejection; };
export type ReadTransportAdmissionResult = (ReadTransportAccepted | ReadTransportRejected);
export declare function admitReadTransportResponse(response: Response, context: ReadTransportContext): Promise<ReadTransportAdmissionResult>;
