#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {generate} from './generate.mjs';
const require=createRequire(import.meta.url),SELF=fileURLToPath(import.meta.url);
function fail(code,message){throw Object.assign(new Error(message),{code});}
function parse(args){const o={};for(let i=0;i<args.length;i++){const a=args[i];if(!['--source','--root','--out-dir','--ajv','--cases'].includes(a)||o[a.slice(2)]!==undefined||!args[i+1]||args[i+1].startsWith('--'))fail('ARGUMENT','unknown, duplicate or incomplete argument '+a);o[a.slice(2)]=path.resolve(args[++i]);}for(const k of ['source','root','out-dir'])if(!o[k])fail('ARGUMENT','required --'+k);return o;}
export function verify(args){const o=parse(args);const check=generate(['--source',o.source,'--root',o.root,'--out-dir',o['out-dir'],'--check']);const source=JSON.parse(fs.readFileSync(o.source,'utf8'));let tool,Ajv,metadataPath,metadata;try{tool=o.ajv??require.resolve('ajv/dist/2020.js');Ajv=require(tool);let d=path.dirname(tool);while(d!==path.dirname(d)&&!fs.existsSync(path.join(d,'package.json')))d=path.dirname(d);metadataPath=path.join(d,'package.json');metadata=JSON.parse(fs.readFileSync(metadataPath,'utf8'));if(metadata.name!=='ajv'||metadata.version!==source.tooling.ajv)fail('TOOL_VERSION','Ajv package/version differs from source tool pin');if(typeof Ajv!=='function')fail('TOOL_UNAVAILABLE','Ajv2020 constructor unavailable');}catch(e){if(e.code==='TOOL_VERSION')throw e;fail('TOOL_UNAVAILABLE','Ajv2020 unavailable; pass --ajv to an existing approved 2020.js; no installation attempted');}
// Standard 2020-12 applicator fragments do not repeat type/required metadata.
// This keeps strict schema-keyword checking while allowing those legal fragments.
const options={strict:true,strictTypes:false,strictRequired:false,allErrors:true,validateFormats:false};
const ajv=new Ajv(options),schemas=[...source.artifacts.filter(x=>x.root),...(source.transport_admission?[{path:source.transport_admission.schema_path,id:source.transport_admission.schema_id,root:source.transport_admission.root,exports:source.transport_admission.exports}]:[])],compiled=[];
for(const a of schemas){const schema=JSON.parse(fs.readFileSync(path.join(o['out-dir'],a.path),'utf8'));if(schema.$schema!==source.schema_dialect||schema.$id!==a.id)fail('SCHEMA','schema identity mismatch');ajv.addSchema(schema);}
for(const a of schemas){const v=ajv.getSchema(a.id);if(typeof v!=='function')fail('SCHEMA','root did not compile');for(const n of a.exports)if(typeof ajv.getSchema(a.id+'#/$defs/'+n)!=='function')fail('SCHEMA','export did not compile '+n);compiled.push({path:a.path,id:a.id,exports:a.exports,status:'COMPILED'});}
const observations=[];if(o.cases){const cases=JSON.parse(fs.readFileSync(o.cases,'utf8'));if(!Array.isArray(cases)||cases.length===0)fail('CASES','nonempty case array required');const ids=new Set();for(const c of cases){if(!c||Object.keys(c).some(k=>!['id','schema','definition','data','valid'].includes(k))||typeof c.id!=='string'||ids.has(c.id)||typeof c.valid!=='boolean'||!Object.hasOwn(c,'data'))fail('CASES','invalid or duplicate case');ids.add(c.id);const a=schemas.find(x=>x.path===c.schema);if(!a)fail('CASES','case schema is outside generated set');const key=a.id+(c.definition?'#/$defs/'+c.definition:'');const validator=ajv.getSchema(key);if(typeof validator!=='function')fail('CASES','case definition unavailable');const valid=validator(c.data);observations.push({id:c.id,schema:c.schema,definition:c.definition??a.root,expected:c.valid,observed:valid,matched:valid===c.valid,error_count:validator.errors?.length??0,errors:validator.errors??[]});}}
const result={status:observations.every(x=>x.matched)?'STRUCTURE_VERIFIED':'STRUCTURAL_EXPECTATION_MISMATCH',check:check.status,compiled,tool:{name:'Ajv2020',version:metadata.version,entry:tool,package_metadata:metadataPath,node:process.versions.node,options,loaded_modules:Object.keys(require.cache)},cases:observations,proof:'Structural JSON Schema validation only; opaque authority, byte digests, semantic resolution, Host time/permission and Read execution are not established.'};if(result.status!=='STRUCTURE_VERIFIED'){console.log(JSON.stringify(result));fail('CASE_MISMATCH','one or more case expectations differ');}return result;}
if(process.argv[1]&&path.resolve(process.argv[1])===SELF){try{console.log(JSON.stringify(verify(process.argv.slice(2))));}catch(e){console.error(JSON.stringify({status:'ERROR',code:e.code??'VERIFICATION_ERROR',message:e.message}));process.exitCode=1;}}
