'use strict';

const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
let scratch;
let copy;
before(() => {
  scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'kdna-format-ownership-'));
  copy = path.join(scratch, 'source');
  fs.cpSync(ROOT, copy, {
    recursive: true,
    filter: (file) =>
      !path
        .relative(ROOT, file)
        .split(path.sep)
        .some((part) => part === '.git' || part === 'node_modules'),
  });
  fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(copy, 'node_modules'), 'junction');
});
after(() => fs.rmSync(scratch, { recursive: true, force: true }));
function run(args = []) {
  return spawnSync(
    process.execPath,
    [path.join(copy, 'scripts/check-format-ownership.cjs'), ...args],
    {
      cwd: copy,
      encoding: 'utf8',
      timeout: 120000,
      maxBuffer: 4 * 1024 * 1024,
    },
  );
}
function mutate(relative, update, check) {
  const file = path.join(copy, relative);
  const before = fs.readFileSync(file);
  try {
    fs.writeFileSync(file, update(before));
    check();
  } finally {
    fs.writeFileSync(file, before);
  }
}
function rejected(result, expected) {
  assert.equal(result.error, undefined);
  assert.equal(result.signal, null);
  assert.equal(result.status, 1, result.stdout + result.stderr);
  assert.match(result.stdout + result.stderr, expected);
}
test('format ownership validates real generator bytes and existing historical owners', () => {
  const result = run();
  assert.equal(result.status, 0, result.stdout + result.stderr);
  assert.match(result.stdout, /FORMAT-OWNERSHIP: MATCH \(49 exact paths;/u);
});
test('format ownership rejects changed historical bytes despite formatter exclusion', () => {
  mutate(
    'specs/canonical-ir-0.6.schema.json',
    (bytes) => Buffer.concat([bytes, Buffer.from(' ')]),
    () => rejected(run(), /format-owned byte length differs/u),
  );
});
test('format ownership rejects changed legacy envelope schema', () => {
  mutate(
    'specs/envelope-aead.schema.json',
    (bytes) => Buffer.concat([bytes, Buffer.from(' ')]),
    () => rejected(run(), /format-owned byte length differs/u),
  );
});
test('format ownership does not trust a generated file plus a forged matching manifest', () => {
  const relative = 'specs/read-contract-0.6.4.schema.json';
  mutate(
    relative,
    (bytes) => Buffer.concat([bytes, Buffer.from(' ')]),
    () => {
      mutate(
        'specs/public-generation-manifest.json',
        (bytes) => {
          const manifest = JSON.parse(bytes);
          const record = manifest.derived.find((row) => row.path === relative);
          const forged = fs.readFileSync(path.join(copy, relative));
          record.bytes = forged.length;
          record.sha256 = crypto.createHash('sha256').update(forged).digest('hex');
          return JSON.stringify(manifest, null, 2) + '\n';
        },
        () => rejected(run(), /GENERATED_DRIFT/u),
      );
    },
  );
});
test('format ownership rejects altered AEAD generated vectors', () => {
  mutate(
    'conformance/envelope-aead/envelope-aead-vector-04-scrypt-multi-slot.json',
    (bytes) => Buffer.concat([bytes, Buffer.from(' ')]),
    () => rejected(run(), /generated bytes differ/u),
  );
});
test('format ownership refuses a broad directory exclusion in its exact block', () => {
  mutate(
    '.prettierignore',
    (bytes) =>
      bytes
        .toString()
        .replace('# END checked byte ownership', 'specs/**\n# END checked byte ownership'),
    () => rejected(run(), /exact path set differs/u),
  );
});
test('format ownership refuses removing an individually owned path', () => {
  mutate(
    '.prettierignore',
    (bytes) => bytes.toString().replace('specs/canonical-ir-0.6.schema.json\n', ''),
    () => rejected(run(), /exact path set differs/u),
  );
});
test('format ownership has no caller supplied skip or expected-hash input', () => {
  rejected(run(['--skip']), /accepts no arguments/u);
});

test('format ownership refuses hiding ordinary files before its checked block', () => {
  mutate(
    '.prettierignore',
    (bytes) => 'scripts/**\n' + bytes.toString(),
    () => rejected(run(), /preexisting format exclusion set differs/u),
  );
});
