// Generated issuer definitions; observations do not grant authority.
import type { AssetCapability, Digest, ReadDiagnosticCode } from '../packages/kdna-core/src/public-contract/types.js';
export type IssuerOptions = { readonly "issuer": string; readonly "signing_key_id": string; readonly "account_id": string; readonly "entitlement_id": string; readonly "entitlement_profile": "account" | "org"; readonly "device_id": string; readonly "device_agreement_public_key": string; readonly "device_signing_public_key": string; readonly "grant_id": string; readonly "status": "active" | "revoked" | "expired"; readonly "status_version": number; readonly "issued_at_ms": number; readonly "refresh_after_ms": number; readonly "offline_grace_until_ms": number; readonly "expires_at_ms": number; readonly "timeout_ms": number; };
export type IssuerSignaturePolicy = { readonly "requireSignature": boolean; readonly "expectedPublicKeyHex": (string | null); };
export type IssuerAdmissionObservation = ({ readonly "status": "accepted"; readonly "asset_capability": AssetCapability; readonly "interpretation": "complete"; } | { readonly "status": "catalog_only"; readonly "asset_capability": AssetCapability; readonly "interpretation": "blocked"; });
export type IssuerAssetDigests = { readonly "A": Digest; readonly "C": Digest; readonly "E": Digest; };
export type IssuerIdentityObservation = { readonly "id": string; readonly "signing_key_id": string; readonly "public_key": string; };
export type IssuerGrantObservation = { readonly "byte_length": number; readonly "digest": Digest; };
export type IssuerIssuedObservation = { readonly "status": "issued"; readonly "grant": IssuerGrantObservation; readonly "asset": IssuerAssetDigests; readonly "issuer": IssuerIdentityObservation; readonly "admission": IssuerAdmissionObservation; readonly "proof": "issuer_output_not_account_or_read_authority"; };
export type IssuerCoreRejectedObservation = { readonly "status": "core_rejected"; readonly "core": { readonly "status": "rejected"; readonly "reason": ReadDiagnosticCode; }; readonly "stage": "asset"; };
export type IssuerFailedObservation = ({ readonly "status": "issuer_failed"; readonly "code": "ISSUER_INPUT_INVALID"; readonly "stage": "input"; } | { readonly "status": "issuer_failed"; readonly "code": "ISSUER_ASSET_PROFILE_UNSUPPORTED"; readonly "stage": "asset"; } | { readonly "status": "issuer_failed"; readonly "code": "ISSUER_ASSET_AUTHENTICATION_FAILED"; readonly "stage": "asset" | "integrity"; } | { readonly "status": "issuer_failed"; readonly "code": "ISSUER_KEY_INVALID"; readonly "stage": "issuer_key"; } | { readonly "status": "issuer_failed"; readonly "code": "ISSUER_GRANT_OPTIONS_INVALID"; readonly "stage": "input" | "grant"; } | { readonly "status": "issuer_failed"; readonly "code": "ISSUER_OUTPUT_INVALID"; readonly "stage": "input" | "asset" | "integrity" | "issuer_key" | "grant"; });
export type IssuerResultObservation = (IssuerIssuedObservation | IssuerCoreRejectedObservation | IssuerFailedObservation);
export type IssuerDescriptor = { readonly "id": "kdna.external-grant-issuer/1"; readonly "version": "1.0.0"; readonly "definition_digest": Digest; readonly "implementation": { readonly "package": "@aikdna/kdna-core"; readonly "version": "0.36.0-rc.r2.7"; }; readonly "exports": readonly ["getExternalGrantIssuerContract", "issueExternalKeyGrantForAsset"]; readonly "limits": { readonly "container_bytes": 26214400; readonly "grant_bytes": 1048576; readonly "timeout_ms_max": 60000; readonly "max_concurrent": 4; }; };
export type IssuerSecrets = { readonly issuerRootKey: Uint8Array; readonly issuerSigningPrivateKeyPkcs8: Uint8Array; readonly signaturePolicy: IssuerSignaturePolicy };
export type IssuanceResult = (IssuerIssuedObservation & { readonly grantBytes: Uint8Array }) | IssuerCoreRejectedObservation | IssuerFailedObservation;
export declare function getExternalGrantIssuerContract(): IssuerDescriptor;
export declare function issueExternalKeyGrantForAsset(input: string | Uint8Array, options: IssuerOptions, secrets: IssuerSecrets): Promise<IssuanceResult>;

