// Generated from specs/public-semantic-source.json; do not edit.
import type { Digest, HostReadContextData, Identifier, PackageMember, PackageSet, PackageSetHandoff, Selection, UInt, VersionLabel } from '../packages/kdna-core/src/public-contract/types.js';
export type PackageSetLocalFailure = "invalid_limits" | "member_limit_exceeded" | "source_bytes_limit_exceeded" | "invalid_member_source" | "invalid_read_request" | "provider_invalid" | "provider_failed" | "provider_observation_invalid" | "cancelled" | "core_unavailable" | "delivery_unconfirmed" | "handoff_invalid";
export type PackageSetLimits = { readonly "maxMembers": 10000; readonly "maxTotalSourceBytes": 104857600; };
export type PackageSetMemberObservationRequest = { readonly "set_id": Identifier; readonly "members": ReadonlyArray<PackageMember>; readonly "selection": Selection; readonly "operation": "isolated_read" | "semantic_merge" | "cross_asset_reference"; readonly "phase": "initial" | "read"; };
export type PackageSetMemberObservationRow = { readonly "member_id": Identifier; readonly "asset_id": Identifier; readonly "asset_version": VersionLabel; readonly "A": Digest; readonly "decision": "allow" | "deny"; readonly "decision_id": Identifier; readonly "host_id": Identifier; readonly "host_epoch": Identifier; readonly "issued_at": UInt; readonly "expires_at": UInt; readonly "current_ms": UInt; };
export type PackageSetMemberObservation = { readonly "decisions": ReadonlyArray<PackageSetMemberObservationRow>; };
export type PackageSetReadObservation = { readonly "context": HostReadContextData; readonly "current_ms": UInt; };
export type PackageSetNodeDescriptor = { readonly "contract": "kdna.package-set-node/0.2.1"; readonly "module_version": "0.2.0"; readonly "core_version": "0.37.0"; readonly "read_version": "0.11.1"; readonly "limits": PackageSetLimits; readonly "local_failures": ReadonlyArray<PackageSetLocalFailure>; readonly "core_callables": ReadonlyArray<Identifier>; readonly "read_callables": ReadonlyArray<Identifier>; readonly "claims": "claims_not_authenticated"; readonly "definition_digest": Digest; };
export type PackageSetNodeSurface = (PackageSet | PackageSetHandoff | PackageSetMemberObservationRequest | PackageSetMemberObservation | PackageSetReadObservation | PackageSetNodeDescriptor);
